######################################################################
# Automatically generated by qmake
######################################################################

TEMPLATE = app
TARGET = 26-pointcloud

INCLUDEPATH += .
QT          += core gui widgets
CONFIG      += debug

LIBQTR3D_PATH = ../../

include(../../libqtr3d.pro)

DEFINES += QT_DEPRECATED_WARNINGS

# Input
SOURCES += main.cc

