######################################################################
# Automatically generated by qmake (3.1) Wed Jul 22 20:38:28 2020
######################################################################

TEMPLATE = app
TARGET = 11-billboard
INCLUDEPATH += .

LIBQTR3D_PATH = ../../
include(../../libqtr3d.pro)

DEFINES += QT_DEPRECATED_WARNINGS

# Input
SOURCES += main.cc

RESOURCES += \
    demodata.qrc
