######################################################################
# Automatically generated by qmake (3.1) Wed Jul 22 20:38:28 2020
######################################################################

TEMPLATE = app
TARGET = 22-follow-camera
INCLUDEPATH += .

LIBQTR3D_PATH = ../../
include(../../libqtr3d.pro)

DEFINES += QT_DEPRECATED_WARNINGS

# Input
SOURCES += main.cc \
    hawksim.cc

RESOURCES += \
    resources.qrc

HEADERS += \
    hawksim.h
