######################################################################
# Automatically generated by qmake
######################################################################

TEMPLATE = app
TARGET = 27-camera-controllers

INCLUDEPATH += .
QT          += core gui widgets
CONFIG      += debug

LIBQTR3D_PATH = ../../

include(../../libqtr3d.pro)

DEFINES += QT_DEPRECATED_WARNINGS

SOURCES += main.cc
