######################################################################
# Automatically generated by qmake
######################################################################

TEMPLATE = app
TARGET = 25-glb-fileformat

INCLUDEPATH += .
QT          += core gui widgets
CONFIG      += debug

LIBQTR3D_PATH = ../../

include(../../libqtr3d.pro)

DEFINES += QT_DEPRECATED_WARNINGS

# Input
SOURCES += main.cc

RESOURCES += demodata.qrc

